# Generated by Django 4.2.4 on 2023-08-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='category',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
