# Generated by Django 4.2.4 on 2023-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_price',
        ),
        migrations.AddField(
            model_name='auction_list',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
