# Generated by Django 4.2.4 on 2023-11-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist_item_id_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='auction_item',
        ),
    ]
