# Generated by Django 4.2.4 on 2023-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_watchlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='image',
            field=models.ImageField(height_field=20, upload_to='auction/images', width_field=20),
        ),
    ]
