# Generated by Django 4.2.4 on 2023-08-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='auction/images'),
        ),
    ]
