# Generated by Django 4.2.4 on 2023-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_bids_auction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='biding_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
