# Generated by Django 4.2.4 on 2023-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_biding_user_id_bids_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='category',
            field=models.CharField(blank=True, choices=[('CLOTHE', 'Clothe'), ('SHOE', 'Shoe'), ('BOOK', 'Book'), ('BAGE', 'Bag'), ('CAR', 'Car'), ('NONE', None)], default=None, max_length=200, null=True),
        ),
    ]
