# Generated by Django 4.2.4 on 2023-08-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_list_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='Auction_list',
            new_name='auction_list',
        ),
    ]
