# Generated by Django 4.2.4 on 2023-11-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_list'),
        ),
    ]
