# Generated by Django 4.2.4 on 2023-08-16 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auction_list_watchlist_auction_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction_list',
            new_name='item_list',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='category',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
