# Generated by Django 4.2.4 on 2023-08-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_list_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='is_active',
        ),
    ]
